## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Formula/Test

# Rules for building the parser.

Formula/Abs.hs Formula/Lex.x Formula/Par.y Formula/Print.hs Formula/Test.hs : Formula.cf
	bnfc --haskell -d Formula.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Formula/Test : Formula/Abs.hs Formula/Lex.hs Formula/Par.hs Formula/Print.hs Formula/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Formula/*.hi Formula/*.o Formula/*.log Formula/*.aux Formula/*.dvi

distclean : clean
	-rm -f Formula/Abs.hs Formula/Abs.hs.bak Formula/ComposOp.hs Formula/ComposOp.hs.bak Formula/Doc.txt Formula/Doc.txt.bak Formula/ErrM.hs Formula/ErrM.hs.bak Formula/Layout.hs Formula/Layout.hs.bak Formula/Lex.x Formula/Lex.x.bak Formula/Par.y Formula/Par.y.bak Formula/Print.hs Formula/Print.hs.bak Formula/Skel.hs Formula/Skel.hs.bak Formula/Test.hs Formula/Test.hs.bak Formula/XML.hs Formula/XML.hs.bak Formula/AST.agda Formula/AST.agda.bak Formula/Parser.agda Formula/Parser.agda.bak Formula/IOLib.agda Formula/IOLib.agda.bak Formula/Main.agda Formula/Main.agda.bak Formula/Formula.dtd Formula/Formula.dtd.bak Formula/Test Formula/Lex.hs Formula/Par.hs Formula/Par.info Formula/ParData.hs Makefile
	-rmdir -p Formula/

# EOF
