-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Formula.

module Formula.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Formula = FExp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = ELit Lit | ENeg Exp | EAnd Exp Exp | EOr Exp Exp | EImply Exp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Lit = LChar Proposition | LNeg Proposition
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Proposition = Proposition String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

